#!/usr/bin/python3 -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Build Collectd for Exascaler system
"""
from installer import collectd_build

if __name__ == "__main__":
    collectd_build.main()
